name: Release GoFSUtil
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
jobs:
  csm-release:
    uses: harishp8889/test-common-github-actions/.github/workflows/csm-release-libs.yaml@test-action
    name: Release Go Client Libraries
